import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faImage, faUser } from '@fortawesome/free-solid-svg-icons'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Tech Social Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.posts}>
          <Image src="https://randomuser.me/api/portraits/women/24.jpg" width={100} height={100}></Image>
          <div className={styles.right_post_bar}>
            <input placeholder="What's in your mind?"></input>
            <div className={styles.tools}>
              <FontAwesomeIcon
                icon={faImage}
                style={{fontSize: 18, color:"white", width: 20 , height:30, marginRight: '10px'}}>
              </FontAwesomeIcon>
              <FontAwesomeIcon
                icon={faImage}
                style={{fontSize: 18, color:"white", width: 20 , height:30, marginRight: '10px'}}>
              </FontAwesomeIcon>
              <FontAwesomeIcon
                icon={faImage}
                style={{fontSize: 18, color:"white", width: 20 , height:30}}>
              </FontAwesomeIcon>
            </div>
            <div className={styles.post_button_container}>
              <div style={{display: 'flex' , alignItems: 'center'}}>
              <FontAwesomeIcon
                  icon={faUser}
                  style={{fontSize: 18, color:"white", width: 20 , height:30}}>
              </FontAwesomeIcon>
              <span style={{marginLeft: "10px"}}>Friends Only View</span>
              </div>
              <button className={styles.post_button}>Post</button>
            </div>
          </div>
        </div>


        
      </main>
    </>
  )
}
